export const MOVE_OUT_STATUS = {
  REQUESTED: 'REQUESTED',
  INSPECTION_PENDING: 'INSPECTION_PENDING',
  SETTLEMENT_PENDING: 'SETTLEMENT_PENDING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  DISPUTED: 'DISPUTED',
} as const;

export type MoveOutStatus = (typeof MOVE_OUT_STATUS)[keyof typeof MOVE_OUT_STATUS];
