import { defineField, defineType } from 'sanity';

export const hostelProfile = defineType({
  name: 'hostelProfile',
  title: 'Hostel Profile',
  type: 'document',
  fields: [
    defineField({
      name: 'name',
      title: 'Hostel name',
      type: 'string',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'name' },
      readOnly: true,
      description: 'Legacy field retained for existing content. The homepage does not render this.',
    }),
    defineField({
      name: 'tagline',
      title: 'Tagline (deprecated)',
      type: 'string',
      readOnly: true,
      description: 'Deprecated: edit the Home Hero title/subtitle instead.',
      validation: (Rule) => Rule.max(160),
    }),
    defineField({
      name: 'about',
      title: 'About (deprecated)',
      type: 'text',
      rows: 4,
      readOnly: true,
      description: 'Deprecated until an About section is visible on the website.',
      validation: (Rule) => Rule.max(900),
    }),
    defineField({
      name: 'mission',
      title: 'Mission (deprecated)',
      type: 'text',
      rows: 3,
      readOnly: true,
      description: 'Deprecated until this field is rendered on the website.',
      validation: (Rule) => Rule.max(600),
    }),
    defineField({
      name: 'foodPhilosophy',
      title: 'Food philosophy (deprecated)',
      type: 'text',
      rows: 3,
      readOnly: true,
      description: 'Deprecated until this field is rendered on the website.',
      validation: (Rule) => Rule.max(600),
    }),
    defineField({
      name: 'phone',
      title: 'Phone number',
      type: 'string',
      description: 'Primary public phone number shown on the website.',
      validation: (Rule) => Rule.max(24),
    }),
    defineField({
      name: 'whatsappNumber',
      title: 'WhatsApp number',
      type: 'string',
      description: 'Use international format without +, for example 919392433422.',
      validation: (Rule) =>
        Rule.regex(/^\d{10,15}$/, {
          name: 'WhatsApp number',
          invert: false,
        }).warning('Use digits only, including country code. Example: 919392433422'),
    }),
    defineField({
      name: 'email',
      title: 'Public email',
      type: 'string',
      validation: (Rule) => Rule.email().warning('Use a valid email address.'),
    }),
    defineField({
      name: 'shortLocation',
      title: 'Short location',
      type: 'string',
      description: 'Compact location shown in the top bar and footer.',
      validation: (Rule) => Rule.max(120),
    }),
    defineField({
      name: 'addressLines',
      title: 'Address lines',
      type: 'array',
      of: [{ type: 'string' }],
      validation: (Rule) => Rule.max(5),
    }),
    defineField({
      name: 'locationTitle',
      title: 'Location section title',
      type: 'string',
      validation: (Rule) => Rule.max(80),
    }),
    defineField({
      name: 'locationDescription',
      title: 'Location description',
      type: 'text',
      rows: 2,
      validation: (Rule) => Rule.max(240),
    }),
    defineField({
      name: 'distanceTitle',
      title: 'Distance title',
      type: 'string',
      validation: (Rule) => Rule.max(80),
    }),
    defineField({
      name: 'distanceDescription',
      title: 'Distance description',
      type: 'string',
      validation: (Rule) => Rule.max(140),
    }),
    defineField({
      name: 'googleMapsUrl',
      title: 'Google Maps URL',
      type: 'url',
      validation: (Rule) =>
        Rule.uri({ scheme: ['http', 'https'] }).warning('Use a valid Google Maps URL.'),
    }),
    defineField({
      name: 'googleMapsEmbedUrl',
      title: 'Google Maps embed URL',
      type: 'url',
      description: 'Paste only the iframe src URL. The website keeps the existing frame size.',
      validation: (Rule) =>
        Rule.uri({ scheme: ['http', 'https'] }).warning('Use the src URL from a Google Maps embed iframe.'),
    }),
    defineField({
      name: 'houseRules',
      title: 'House rules summary (deprecated)',
      type: 'array',
      of: [{ type: 'string' }],
      readOnly: true,
      description: 'Deprecated: public rules are not currently rendered on the landing page.',
      validation: (Rule) => Rule.max(12),
    }),
    defineField({
      name: 'ownerMessage',
      title: 'Owner message',
      type: 'text',
      rows: 3,
      validation: (Rule) => Rule.max(500),
    }),
    defineField({
      name: 'ownerName',
      title: 'Owner name',
      type: 'string',
      validation: (Rule) => Rule.max(120),
    }),
    defineField({
      name: 'ownerPhoto',
      title: 'Owner photo',
      type: 'marketingImage',
    }),
    defineField({
      name: 'gallery',
      title: 'Profile gallery (deprecated)',
      type: 'array',
      of: [{ type: 'marketingImage' }],
      readOnly: true,
      description: 'Deprecated: use the Gallery collection and link it from Home Landing Page.',
      validation: (Rule) => Rule.max(20),
    }),
  ],
  preview: {
    select: { title: 'name', subtitle: 'shortLocation', media: 'ownerPhoto.image' },
  },
});
