import { defineField, defineType } from 'sanity';

export const testimonial = defineType({
  name: 'testimonial',
  title: 'Testimonial',
  type: 'document',
  fields: [
    defineField({
      name: 'name',
      title: 'Display name',
      type: 'string',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'details',
      title: 'Details (deprecated)',
      type: 'string',
      description: 'Example: 3rd Year · B.Tech CSE · SNIST',
      readOnly: true,
      validation: (Rule) => Rule.max(180),
    }),
    defineField({
      name: 'role',
      title: 'Role',
      type: 'string',
      description: 'Example: Current tenant, Parent, Former tenant.',
      validation: (Rule) => Rule.max(120),
    }),
    defineField({
      name: 'quote',
      title: 'Quote (deprecated)',
      type: 'text',
      rows: 4,
      readOnly: true,
      description: 'Deprecated: use Review.',
      validation: (Rule) => Rule.max(700),
    }),
    defineField({
      name: 'review',
      title: 'Review',
      type: 'text',
      rows: 4,
      validation: (Rule) => Rule.required().max(700),
    }),
    defineField({
      name: 'rating',
      title: 'Rating',
      type: 'number',
      initialValue: 5,
      validation: (Rule) => Rule.min(1).max(5),
    }),
    defineField({
      name: 'duration',
      title: 'Stay duration / label (deprecated)',
      type: 'string',
      readOnly: true,
      description: 'Deprecated: use Role.',
      validation: (Rule) => Rule.max(120),
    }),
    defineField({
      name: 'verificationType',
      title: 'Verification type (deprecated)',
      type: 'string',
      readOnly: true,
      description: 'Deprecated for the public landing page.',
      options: {
        layout: 'radio',
        list: [
          { title: 'Current tenant', value: 'CURRENT_TENANT' },
          { title: 'Former tenant', value: 'FORMER_TENANT' },
          { title: 'Parent', value: 'PARENT' },
        ],
      },
    }),
    defineField({
      name: 'approvedBy',
      title: 'Approved by (deprecated)',
      type: 'string',
      readOnly: true,
      description: 'Deprecated for the public landing page.',
      validation: (Rule) => Rule.max(120),
    }),
    defineField({
      name: 'approvedAt',
      title: 'Approved at (deprecated)',
      type: 'datetime',
      readOnly: true,
      description: 'Deprecated for the public landing page.',
    }),
    defineField({
      name: 'photo',
      title: 'Photo (deprecated)',
      type: 'marketingImage',
      readOnly: true,
      description: 'Deprecated: use Image.',
    }),
    defineField({
      name: 'image',
      title: 'Image',
      type: 'marketingImage',
    }),
    defineField({
      name: 'displayOrder',
      title: 'Display order',
      type: 'number',
      initialValue: 10,
      validation: (Rule) => Rule.integer().min(0),
    }),
    defineField({
      name: 'isActive',
      title: 'Active',
      type: 'boolean',
      initialValue: true,
    }),
  ],
  preview: {
    select: { title: 'name', subtitle: 'role', media: 'image.image' },
  },
});
