export const dynamic = "force-dynamic";
export const runtime = "nodejs";

import { NextRequest } from "next/server";
import { getSession, apiResponse, apiError } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { requireHostelBelongsToOwner } from "@/lib/security/scoped-query";

const ALLOWED_MANUAL_TYPES = ["MAINTENANCE", "FINE", "EXTRA_CHARGE", "OTHER"];

/**
 * POST /api/payments/obligations
 * Manually create a non-RENT obligation (MAINTENANCE, FINE, EXTRA_CHARGE).
 * RENT obligations are auto-generated by the rent generation service — NOT created here.
 *
 * Body: {
 *   tenant_id,
 *   obligation_type: "MAINTENANCE" | "FINE" | "EXTRA_CHARGE" | "OTHER",
 *   amount,
 *   rent_month,   // ISO date string — the month this charge belongs to
 *   due_date,     // ISO date string
 *   notes?
 * }
 * Auth: OWNER or ADMIN only
 */
export async function POST(req: NextRequest) {
  const session = await getSession(req);
  if (!session || !["OWNER", "ADMIN"].includes(session.role)) {
    return apiError("Forbidden", "FORBIDDEN", 403);
  }

  let obligation_type_label = "charge";
  try {
    const body = await req.json();
    const { tenant_id, obligation_type, amount, rent_month, due_date, notes } = body;
    obligation_type_label = obligation_type || "charge";

    // Validation
    if (!tenant_id) return apiError("tenant_id is required", "VALIDATION_ERROR", 400);
    if (!ALLOWED_MANUAL_TYPES.includes(obligation_type)) {
      return apiError(
        `obligation_type must be one of: ${ALLOWED_MANUAL_TYPES.join(", ")}`,
        "VALIDATION_ERROR", 400
      );
    }
    if (!amount || typeof amount !== "number" || amount <= 0) {
      return apiError("amount must be a positive number", "VALIDATION_ERROR", 400);
    }
    if (!rent_month) return apiError("rent_month is required", "VALIDATION_ERROR", 400);
    if (!due_date) return apiError("due_date is required", "VALIDATION_ERROR", 400);

    const rentMonthDate = new Date(rent_month);
    const dueDateDate = new Date(due_date);
    if (isNaN(rentMonthDate.getTime())) return apiError("rent_month is not a valid date", "VALIDATION_ERROR", 400);
    if (isNaN(dueDateDate.getTime())) return apiError("due_date is not a valid date", "VALIDATION_ERROR", 400);

    // Verify tenant belongs to this owner
    const tenant = await prisma.tenants.findUnique({
      where: { id: tenant_id },
      select: {
        owner_id: true,
        hostel_id: true,
        allocations: {
          where: { is_active: true },
          select: { id: true, hostel_id: true, room: { select: { hostel_id: true } } },
        },
      },
    });

    if (!tenant) return apiError("Tenant not found", "NOT_FOUND", 404);

    const ownerId = session.role === "OWNER" ? session.sub : session.sub;
    if (tenant.owner_id !== ownerId) {
      return apiError("Tenant does not belong to your account", "FORBIDDEN", 403);
    }

    if (!tenant.hostel_id) {
      return apiError("Tenant is missing hostel context", "HOSTEL_CONTEXT_REQUIRED", 400);
    }
    await requireHostelBelongsToOwner(ownerId, tenant.hostel_id);

    const activeAllocation = tenant.allocations[0] || null;
    const activeAllocationId = activeAllocation?.id || null;
    if (activeAllocation && activeAllocation.hostel_id !== tenant.hostel_id) {
      return apiError("Active allocation hostel does not match tenant hostel", "HOSTEL_CONTEXT_MISMATCH", 409);
    }
    if (activeAllocation?.room?.hostel_id && activeAllocation.room.hostel_id !== tenant.hostel_id) {
      return apiError("Active room hostel does not match tenant hostel", "HOSTEL_CONTEXT_MISMATCH", 409);
    }

    // Create the obligation
    // Note: @@unique([allocation_id, rent_month, obligation_type]) prevents duplicate
    // maintenance charges for the same month+allocation. This is intentional.
    const obligation = await prisma.rent_obligations.create({
      data: {
        tenant_id,
        owner_id: ownerId,
        hostel_id: tenant.hostel_id,
        allocation_id: activeAllocationId,
        obligation_type,
        amount,
        total_amount: amount,
        rent_month: rentMonthDate,
        due_date: dueDateDate,
        status: "PENDING",
      },
    });

    return apiResponse(obligation, 201);
  } catch (error: any) {
    const msg = String(error?.message ?? error);
    // Prisma unique constraint: duplicate obligation for this month + type + allocation
    if (msg.includes("Unique constraint") || msg.includes("P2002")) {
      return apiError(
        `A ${obligation_type_label} obligation already exists for this tenant/month. ` +
        "Update the existing one or choose a different month.",
        "VALIDATION_ERROR", 409
      );
    }
    if (msg.includes("NOT_FOUND")) return apiError(msg, "NOT_FOUND", 404);
    if (msg.includes("FORBIDDEN")) return apiError(msg, "FORBIDDEN", 403);
    return apiError(msg, "INTERNAL_ERROR", 500);
  }
}
