export { siteSettings } from './siteSettings'
export { hostel } from './hostel'
export { testimonial } from './testimonial'
export { faq } from './faq'
export { categoryRating } from './categoryRating'
export { food } from './food'
export { parentTrust } from './parentTrust'
